language: java
before_script: cd 12f_app
script: mvn clean install
deploy:
  edge: true
  provider: cloudfoundry
  username: mart.reose@smit.ee
  api: https://api.run.pivotal.io
  organization: m2rt
  space: staging
  password:
    secure: obqsSNFKoo/Oa1mmSGCoO7EV2tl9zQXG47fCHbyB5xfqsK8un9hC+RaugfTD80ABoAncuGSF0PsOC/CopMspQj9+I1+Pw2l6sCY/bdZOknYLohW7XqGbx/EyMlv8/St7iBrCLTUSBG06TF4avLeiSZ2d1Q4M5RB1GhzKMioCue6B5xSPBKx1DppJnj/ah8ahJve4W3HrqFzrfXxxSEEjTHMmzDpBabbDE0uto7B7a2XQFgxIqy8B1y9IWsvPgJbWUeH9gFcjK4KVeB4kiekRM6ALhMbp23dtT6PfRYpQ8mGh+ClNJGvebFI9qjZ45fXIaLXf7iZmZU/F5Vun4Smb8h3bsQx/OQ0QPLsRKkzwJ9l6e7sIehTpitn8vAHa8UbUk64Xd3yKbRmmV9XsffPpNrW8xdH30wLVewsfMgHdbLLSpDVQTqoshSAQXnvgaKGHAMpq8BrecZIGNBttEZfqewYNqCbXTsIzUEcWX3uoxIApb4glNPZ08LMbVM2YEaSo28GwnwbBKGcnJRXzdydCVjdUvrOrMUu09P2D51Kg1aLKTZjgXFpF2eiRz7BtTyz5xJuTzjhrKOzDaNwpchQhvrWVDcJijcfcx6hlytxpJVzNfhsEapnvPlkXyUxsqv13aENHUaqsdogTIPYuKYkgeODfjW6w+rFJR51ZAR1VF6w=
